#apkFile: /Users/junayed/Documents/NecessaryDocs/GeorgeMasonUniversity/Research/Projects/BURTTool/burt/CrashScope/apps.txt
apkFile: /Volumes/Education/GitHub/burt/crashscope/apps.txt
#aaptPath: /Users/junayed/Library/Android/sdk/build-tools/30.0.3
aaptPath: /Users/asaha02/Library/Android/sdk/build-tools/30.0.3
#outputFolder: /Users/junayed/Documents/NecessaryDocs/GeorgeMasonUniversity/Research/Projects/BURTTool/burt/CrashScope/Output
outputFolder: /Volumes/Education/GitHub/burt/crashscope/output_new
#scriptsPath: /Users/junayed/Documents/NecessaryDocs/GeorgeMasonUniversity/Research/Projects/BURTTool/burt/CrashScope/lib/scripts
scriptsPath: /Volumes/Education/GitHub/burt/crashscope/lib/scripts
#androidSDKPath: /Users/junayed/Library/Android/sdk
androidSDKPath: /Users/asaha02/Library/Android/sdk
GUITraversal: ["top-down", "bottom-up"] #top-down or bottom-up or both
textEntry: "expected-text" #"no-text" or "expected-text" or "unexpected-text"
avdPort: 5554
adbPort: 5037
executionNum: 1